function Yout = inpaint_prob_map(Yin, useSmoothed)
% INPAINT_PROB_MAP  Inpaints missing membrane probabilities.
%
%      Yout = inpaint_prob_map(Yin);
%
%    where,
%      Yin : a tensor of probability estimates with shape (width,height,#slices)
%            Any value < 0 will be inpainted.
%      Yout : the inpainted result (same size as Yin)
%
%   Use this to generate a complete probability cube from a
%   cube of partial evaluations (generated by emcnn.py).
%
%   Note that the "inpaint" subdirectory needs to be in the search
%   path prior to calling this function.
%
% October 2015, mjp

if nargin < 2, useSmoothed = 1; end

assert(length(size(Yin)) == 3);

if ~exist('inpaintn')
  error('No function inpaintn(); Is the "inpaint" subdirectory in the matlab search path?');
end

if ~any(isnan(Yin(:)))
    fprintf('[%s]: No NaN values in input image - nothing to do\n', mfilename)
    Yout = Yin;
    return
end



fprintf('[%s]: recovering missing values (%0.2f%% of volume)\n', ...
  mfilename, 100*sum(isnan(Yin(:))) / numel(Yin));


% For now, we inpaint a slice at a time.  
% This could be done in 3d; exploring this is an area of future work.
tic
Yout = zeros(size(Yin));
for ii = 1:size(Yin,3)
  Yi = Yin(:,:,ii);

  % do inpainting; remap output to [0,1]
  Yr = inpaintn(Yi);
  Yr = Yr - min(Yr(:));
  Yr = Yr / (max(Yr(:)) - min(Yr(:)));

  % Can optionally replace smoothed values with original values...
  if ~useSmoothed
      Yr(isfinite(Yi)) = Yi(isfinite(Yi));
  end

  Yout(:,:,ii) = Yr;

  fprintf('[%s]: finished slice %d (of %d); total time: %0.2f sec\n', ...
    mfilename, ii, size(Yin,3), toc);
end
